import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const montserrat = Montserrat({
	variable: "--font-montserrat",
	subsets: ["latin"],
});

export const metadata = {
	title: "LeetWrite",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${montserrat.variable} ${geistMono.variable} antialiased`}
			>
				<Suspense fallback={null}>{children}</Suspense>
			</body>
		</html>
	);
}
